HyperReview#hyperreview
  Worker#worker
    Scheduler#scheduler
    JobQueue#queue
    JobJournal#journal
  Intake#intake
    GitHubSource#github
    RepositoryAllowlist#repositories
      Repository#specgraph
      Repository#hypercode
    EligibilityPolicy#eligibility
    RevisionSnapshot#snapshot
    EvidencePack#evidence
  Analysis#analysis
    ModelGateway#modelgateway
      Backend#backend
    PairedProjection#projection
      IdentityMap#identities
    ClaimLedger#claims
  Validation#validation
    HypercodeToolchain#hypercode-validator
    ProvenanceCheck#provenance
    ScopeCheck#scope
    ArtifactBundle#artifacts
  Presentation#presentation
    MarkdownRenderer#renderer
    LocalPreview#preview
  Delivery#delivery
    PublicationGate#publication-gate
    GitHubPublisher#publisher
  Observability#observability
    ExperimentTracking#tracking
      MLflowAdapter#mlflow
      WorkflowTrace#traces
    PilotEvaluation#evaluation
      EvaluationCases#cases
      ScorerSet#scorers
      ReviewerFeedback#feedback
      QualityReports#reports
        EvidentlyAdapter#evidently
      BaselineComparison#baseline
      RegressionPolicy#regression
  Operations#operations
    StateStore#state
    TrackingSpool#tracking-spool
    BudgetPolicy#budget
    AuditLog#audit
    CredentialBroker#credentials
    RuntimeIsolation#isolation
  DevelopmentTooling#development-tools
    ProjectQualityMeasurement#project-quality
      SpecificationMetricsTool#specificationmetrics
      QualitySnapshotHistory#quality-history
